-- Migration script to upgrade a pre-MS4 database (the schema that
-- ships on the `main` branch) to the schema expected by the MS4
-- feature branches.  Run this with:
--   psql $DB_NAME -f db/migrations/ms4_schema_upgrade.sql
-- It is safe to run the script multiple times.

BEGIN;

-- ------------------------------------------------------------------
-- Users: add address/balance columns if they do not exist yet.
-- ------------------------------------------------------------------
ALTER TABLE IF EXISTS Users
    ADD COLUMN IF NOT EXISTS address VARCHAR(255);

UPDATE Users
SET address = COALESCE(address, 'Address TBD');

ALTER TABLE IF EXISTS Users
    ALTER COLUMN address SET NOT NULL;

ALTER TABLE IF EXISTS Users
    ADD COLUMN IF NOT EXISTS balance DECIMAL(12,2);

UPDATE Users
SET balance = COALESCE(balance, 0);

ALTER TABLE IF EXISTS Users
    ALTER COLUMN balance SET NOT NULL;

ALTER TABLE IF EXISTS Users
    ALTER COLUMN balance SET DEFAULT 0;

ALTER TABLE IF EXISTS Users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE Users
SET created_at = COALESCE(created_at, now());

ALTER TABLE IF EXISTS Users
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE IF EXISTS Users
    ALTER COLUMN created_at SET DEFAULT now();

-- ------------------------------------------------------------------
-- Categories table + seed data (idempotent).
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Categories (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO Categories (id, name) VALUES
    (1, 'Frozen Treats'),
    (2, 'Beverages & Bar'),
    (3, 'Luxury Collectibles'),
    (4, 'Fine Art'),
    (5, 'Home Fragrance & Bath'),
    (6, 'Kitchen & Dining'),
    (7, 'Books & Stationery'),
    (8, 'Tech Gifts'),
    (9, 'Games & Toys'),
    (10, 'Fashion & Jewelry')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;

SELECT setval(
    pg_get_serial_sequence('categories', 'id'),
    COALESCE((SELECT MAX(id) + 1 FROM Categories), 1),
    false
);

-- ------------------------------------------------------------------
-- Products: add new metadata columns + defaults.
-- ------------------------------------------------------------------
ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS category_id INT REFERENCES Categories(id);

ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS category_name VARCHAR(255);

ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS creator_id INT REFERENCES Users(id);

UPDATE Products
SET description = COALESCE(description, '')
WHERE description IS NULL;

WITH fallback AS (
    SELECT id, name
    FROM Categories
    WHERE name = 'Frozen Treats'
    UNION ALL
    SELECT id, name
    FROM Categories
    ORDER BY id
    LIMIT 1
)
UPDATE Products
SET category_id = COALESCE(Products.category_id, fallback.id),
    category_name = COALESCE(Products.category_name, fallback.name)
FROM fallback
WHERE Products.category_id IS NULL
   OR Products.category_name IS NULL;

ALTER TABLE Products
    ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE Products
    ALTER COLUMN category_name SET NOT NULL;

UPDATE Products
SET price = 0
WHERE price IS NULL;

ALTER TABLE Products
    ALTER COLUMN price SET NOT NULL;

ALTER TABLE Products
    ALTER COLUMN available SET DEFAULT TRUE;

-- ------------------------------------------------------------------
-- Orders + OrderItems tables (used by checkout pipeline).
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    total_amount DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0)
);

CREATE INDEX IF NOT EXISTS orders_user_created_idx
    ON Orders(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS OrderItems (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL REFERENCES Orders(id) ON DELETE CASCADE,
    listing_id INT NOT NULL REFERENCES ProductSeller(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    subtotal DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),
    fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
    fulfilled_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS order_items_order_idx
    ON OrderItems(order_id);

CREATE INDEX IF NOT EXISTS order_items_seller_idx
    ON OrderItems(seller_id);

-- ------------------------------------------------------------------
-- Cart table: rebuild it if we still have the old (user_id, product_id)
-- structure, otherwise leave it alone.
-- ------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'cart'
          AND column_name = 'listing_id'
    ) THEN
        DROP TABLE IF EXISTS Cart CASCADE;

        CREATE TABLE Cart (
            user_id INTEGER NOT NULL REFERENCES Users(id),
            product_id INTEGER NOT NULL REFERENCES Products(id),
            listing_id INTEGER NOT NULL REFERENCES ProductSeller(id),
            seller_id INTEGER NOT NULL REFERENCES Users(id),
            unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
            quantity INTEGER NOT NULL CHECK (quantity > 0),
            PRIMARY KEY (user_id, listing_id)
        );

        CREATE INDEX cart_user_idx ON Cart(user_id);
    END IF;
END $$;

COMMIT;
